- alias: Reboot Nabaztag at start
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: shell_command.nab_reboot
    - service: switch.turn_on
      entity_id: switch.nabaztaglife
#******************************************************************************
- alias: "Startup setup"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: group.set_visibility
      entity_id: group.nabaztag_locale_setup
      data:
        visible: False
    - service: input_number.set_value
      data_template:
        entity_id: input_number.bitcoin_previous_exchange_rate
        value: "{{ states('sensor.exchange_rate_1_btc') }}"