homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include misc/customize.yaml
  packages: !include_dir_named packages
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

recorder:
  purge_keep_days: 14
  db_url: !secret db_url
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /config/www/vl/voice

# Cloud
#cloud:

hassio:

###########INCLUDES#####
alert: !include_dir_merge_named alerts/
automation: !include automations.yaml
device_tracker: !include_dir_list device_trackers/
input_boolean: !include misc/input_boolean.yaml
input_select: !include misc/input_select.yaml
input_number: !include misc/input_number.yaml
input_text: !include misc/input_text.yaml
#input_slider: !include misc/input_slider.yaml
media_player: !include_dir_list media_player/
binary_sensor: !include_dir_list binary_sensors/
sensor: !include_dir_list sensors/
light: !include_dir_list lights/
shell_command: !include misc/shell_commands.yaml
switch: !include_dir_list switches/
script: !include_dir_merge_named scripts/
group: !include groups.yaml
weather: !include_dir_list weather/
scene: !include_dir_list scenes/
#weblink: !include misc/weblinks.yaml
zone: !include_dir_list zones/
camera: !include_dir_list cameras/


##########OTHER#####
google_assistant:
  project_id: hass-ce8ef
  client_id: !secret ga_client_id
  access_token: !secret ga_access_token
  agent_user_id: rgn-hass
  api_key: !secret ga_api_key
  exposed_domains:
    - switch
    - light
    - group
    - media_player

tradfri:
  host: !secret tradfri_ip

mqtt:
  broker: !secret mqtt_broker_ip
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

ffmpeg:
  
ios: