alias: "Nabaztag Right Ear"
trigger:
  platform: state
  entity_id: input_number.nabaztag_right_ear
action:
  service_template: >
    {% if is_state("input_number.nabaztag_right_ear", "0.0") %} shell_command.nab_ear_right_0
    {% elif is_state("input_number.nabaztag_right_ear", "1.0") %} shell_command.nab_ear_right_1
    {% elif is_state("input_number.nabaztag_right_ear", "2.0") %} shell_command.nab_ear_right_2
    {% elif is_state("input_number.nabaztag_right_ear", "3.0") %} shell_command.nab_ear_right_3
    {% elif is_state("input_number.nabaztag_right_ear", "4.0") %} shell_command.nab_ear_right_4
    {% elif is_state("input_number.nabaztag_right_ear", "5.0") %} shell_command.nab_ear_right_5
    {% elif is_state("input_number.nabaztag_right_ear", "6.0") %} shell_command.nab_ear_right_6
    {% elif is_state("input_number.nabaztag_right_ear", "7.0") %} shell_command.nab_ear_right_7
    {% elif is_state("input_number.nabaztag_right_ear", "8.0") %} shell_command.nab_ear_right_8
    {% elif is_state("input_number.nabaztag_right_ear", "9.0") %} shell_command.nab_ear_right_9
    {% elif is_state("input_number.nabaztag_right_ear", "10.0") %} shell_command.nab_ear_right_10
    {% elif is_state("input_number.nabaztag_right_ear", "11.0") %} shell_command.nab_ear_right_11
    {% elif is_state("input_number.nabaztag_right_ear", "12.0") %} shell_command.nab_ear_right_12
    {% elif is_state("input_number.nabaztag_right_ear", "13.0") %} shell_command.nab_ear_right_13
    {% elif is_state("input_number.nabaztag_right_ear", "14.0") %} shell_command.nab_ear_right_14
    {% elif is_state("input_number.nabaztag_right_ear", "15.0") %} shell_command.nab_ear_right_15
    {% elif is_state("input_number.nabaztag_right_ear", "16.0") %} shell_command.nab_ear_right_16
    {% else %}
      shell_command.nab_abort
    {% endif %}